name: doc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      #with: 
      #  ref: master
    
    #Install dependencies
    - name: Dependencies
      run: | 
        sudo apt update 
        sudo apt install -y zip doxygen graphviz
        doxygen --version
    
    # Build the HTML documentation
    - name: Doxygen
      run: |
        chmod +x scripts/generate_doc.sh
        scripts/generate_doc.sh
    
    # Deploy the HTML documentation to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages